/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nuce.edu.daltudm.springdaltudm.Controller;

import java.util.List;
import nuce.edu.daltudm.springdaltudm.Entity.Detail;
import nuce.edu.daltudm.springdaltudm.Repository.DetailRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 *
 * @author Khanh Trinh
 */
@RestController
@RequestMapping("/Detail")
public class DetailConttroller {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private DetailRepository detailRepository;

    @GetMapping(path = "/all")
    public List<Detail> list() {
        return detailRepository.findAll();
    }

    @PostMapping(path = "/add")
    public ResponseEntity<?> addDetail(@RequestBody Detail input) {
        detailRepository.save(input);
        return new ResponseEntity<>(null,
                HttpStatus.valueOf(201));
    }

    @DeleteMapping("/delete/{id}")
    public ResponseEntity<?> deleteDetail(@PathVariable Long id) {
        detailRepository.deleteById(id);
        return new ResponseEntity<>(null,
                HttpStatus.valueOf(204));
    }
}
